### ISSUE TITLE
[Bug] 哔哩轻小说的Cover URL中存在非法字符

### ISSUE THREAD

**Issue by GOUKOU007** [lightnovel-center/linovelib2epub#10]
现在哔哩轻小说的Cover URL中存在`?`字符，例如`https://w.linovelib.com/files/article/image/2/2044/2044s.jpg?540916`。windows系统不允许路径中存在`?`，这会导致下载图像时Cover无法正常保存，进而导致生成epub时因找不到Cover图像报错。

目前我没有想出通用的修复方案，也许需要将URL和filename存储在两个Dict中，或者把现有image_dict的值改成List以同时保存URL和filename？

测试用URL：`https://w.linovelib.com/novel/3626.html`
报错：
``` python
OSError: [Errno 22] Invalid argument: 'images/image-3-3626-3626s.jpg?553400'
```

临时解决方案为在[src/linovelib2epub/spider/linovelib_mobile_spider.py](https://github.com/lightnovel-center/linovelib2epub/blob/main/src/linovelib2epub/spider/linovelib_mobile_spider.py#L75)中的`_crawl_book_basic_info`方法中，找到：
```
 book_cover_url = soup.find('img', {'class': 'book-cover'})['src']
```
改为：
```
 book_cover_url = soup.find('img', {'class': 'book-cover'})['src'].split("?")[0]
```

**Comment by wdpm** [comment]
感谢反馈。以前我的确没有到这个问题。其实你的临时修复方法就是我认为的最佳修复了。
> 目前我没有想出通用的修复方案，也许需要将URL和filename存储在两个Dict中，或者把现有image_dict的值改成List以同时保存URL和filename？
这种考虑会增加代码复杂度，我不认为是个好方法，因为不会往这方面去思考。

临时修复对于该问题足够，
```
book_cover_url = soup.find('img', {'class': 'book-cover'})['src'].split("?")[0]
```
