### ISSUE TITLE
下載後的EPUB 內容只有標題, 內文全是NONE

### ISSUE THREAD

**Issue by seinteller7** [lightnovel-center/linovelib2epub#22]
``` python
from linovelib2epub.linovel import Linovelib2Epub

# warning!: must run within __main__ module guard due to process spawn issue.
if __name__ == '__main__':
    linovelib_epub = Linovelib2Epub(book_id=3279,select_volume_mode=True)
    linovelib_epub.run()
```

用以上CODE下載回來的EPUB 沒有內文.全顯示成"NONE"。幾個月前一直在用,沒有問題。這幾天就用不了, 謝謝

**Comment by wdpm** [comment]
该问题已经得到确认，但是需要进一步的问题排查。@seinteller7

**Comment by seinteller7** [comment]
謝謝!

**Comment by wdpm** [comment]
@seinteller7 已修复

**Comment by seinteller** [comment]
已輸入 pip install linovelib2epub --upgrade 更新, 但下載來的EPUB還是NONE, 我的更新正確程序正確?

**Comment by seinteller** [comment]
不太懂用「源码克隆模式」... 先試試

**Comment by seinteller** [comment]
不好意思, 請問這錯誤可如何修正?

(venv) C:\Windows\system32>py -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

(venv) C:\Windows\system32>
(venv) C:\Windows\system32>python -m pip install -e .
Obtaining file:///C:/Windows/system32
ERROR: file:///C:/Windows/system32 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by wdpm** [comment]
> 不好意思, 請問這錯誤可如何修正?
> 
> (venv) C:\Windows\system32>py -m pip install -r requirements.txt ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
> 
> (venv) C:\Windows\system32> (venv) C:\Windows\system32>python -m pip install -e . Obtaining file:///C:/Windows/system32 ERROR: file:///C:/Windows/system32 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

抱歉，我的文档说明不够清晰，可能误导了你。我重新更新了源码模式的使用说明。
你所有指令都保证在项目根目录下（`linovelib2epub`）之下操作，理论上就可以正常运行了。

**Comment by seinteller** [comment]
謝謝, 我想應該成功更新了, 但下載卻出現:
"
2023-10-21,11:01:44 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:70    Succeed to get the novel of book_id: 3279
2023-10-21,11:01:45 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:229   Succeed to get the catalog of book_id: 3279
2023-10-21,11:01:45 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:258   volume: 全一册
2023-10-21,11:01:45 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:273   chapter : 作品相关
2023-10-21,11:01:46 WARNING  LinovelibMobileSpider  utils.py                  :45    Request https://w.linovelib.com/novel/3279/167340.html succeed but data is empty.
2023-10-21,11:05:29 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:70    Succeed to get the novel of book_id: 3279
2023-10-21,11:05:30 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:229   Succeed to get the catalog of book_id: 3279
2023-10-21,11:05:30 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:258   volume: 全一册
2023-10-21,11:05:30 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:273   chapter : 作品相关
2023-10-21,11:05:32 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:352   Processing page... https://w.linovelib.com/novel/3279/167340.html
2023-10-21,11:05:32 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:273   chapter : 第一章 寻死少女
2023-10-21,11:05:39 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:352   Processing page... https://w.linovelib.com/novel/3279/167544.html
2023-10-21,11:05:40 INFO     LinovelibMobileSpider  linovelib_mobile_spider.py:352   Processing page... https://w.linovelib.com/novel/3279/167544_2.html
2023-10-21,11:05:40 WARNING  LinovelibMobileSpider  utils.py                  :45    Request https://w.linovelib.com/novel/3279/167544_3.html succeed but data is empty.
"
看來是網路看得比較緊?最近

**Comment by wdpm** [comment]
> 2023-10-21,11:05:40 WARNING LinovelibMobileSpider utils.py :45 Request https://w.linovelib.com/novel/3279/167544_3.html succeed but data is empty.
该问题不是合理的行为，已被复现，有关具体原因还需要进一步排查。

**Comment by wdpm** [comment]
> Fatal error: Uncaught RedisException: Connection refused in /home/wwwroot/m.linovelib.com/global.php:554 Stack trace: #0 /home/wwwroot/m.linovelib.com/global.php(554): Redis->connect('127.0.0.1', 6379) #1 /home/wwwroot/m.linovelib.com/global.php(282): JieqiCacheRedis->__construct(Array) #2 /home/wwwroot/m.linovelib.com/global.php(2758): JieqiCache::getInstance('redis', Array) #3 /home/wwwroot/m.linovelib.com/modules/article/articleinfo.php(5): include_once('/home/wwwroot/m...') #4 {main} thrown in /home/wwwroot/m.linovelib.com/global.php on line 554

它的redis连接池已经满了，估计它要开限流或者加钱升级资源了。

**Comment by wdpm** [comment]
@seinteller 等后续修复吧，我已在本地成功解决此问题。

**Comment by seinteller** [comment]
謝!

**Comment by wdpm** [comment]
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>错误_哔哩轻小说</title>
<meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width" />
<meta content="yes" name="apple-mobile-web-app-capable" />
<meta content="black" name="apple-mobile-web-app-status-bar-style" />
<meta content="telephone=no" name="format-detection" />
<link href="https://w.linovelib.com/themes/zhmb/css/login.css?v505a2" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/scripts/darkmode.js"></script>
</head>
<body>
<section class="aui-flexView"><header class="aui-navBar aui-navBar-fixed"><a href="javascript:history.go(-1)" class="aui-navBar-item"><i class="icon icon-return"></i></a>
<div class="aui-center">
<h2 class="aui-center-title">错误原因</h2>
</div>
</header>
<section class="aui-scrollView">
<div class="aui-ver-head">
<div class="center-header"></div>
</div>
<div class="aui-ver-form">
網站正在被攻擊!<br/><br/>error: Connection refused<br><br>
</div>
</section>
</section>
<script>(function(){var js = "window['__CF$cv$params']={r:'81971d4a0e4c0464',t:'MTY5Nzg2NjI5MS41OTkwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>
</html>
</body>
</html>
```
> 網站正在被攻擊!

先别考虑 w.linovelib.com 了，它目前应该被打爆了。

**Comment by wdpm** [comment]
> https://w.linovelib.com/
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/ce412032-0485-40dd-b58f-99e237781e2d)

要考虑 web 站 www 了。

**Comment by wdpm** [comment]
@seinteller 已修复哔哩轻小说的请求headers字段问题，以及初步实现真白萌masiro的小说爬取。具体请更新源码并阅读使用文档。

**Comment by wdpm** [comment]
@seinteller linovelib mobile book_id 3279 我本地是可以的。而且从你上面的log来看，似乎没什么问题。

**Comment by seinteller** [comment]
下載下來的EPUB:
https://1drv.ms/u/c/72f35d40f2182dd0/EVDIgcD0NBRMqiYCXeQE-jsB-018RtNczjcbgDdLTP1Y-g?e=aYoaFV
用不同的軟件打開內容還是none none （連結如有需要可下載後刪除

**Comment by seinteller** [comment]
可能估計到是什麼原因了... 懷疑是舊的code 完全移除, 請問如果想完全移除 安裝了的檔案, 請如何?謝謝

**Comment by wdpm** [comment]
@seinteller 你用的什么聊天工具软件，远程协助吧。我本地是没法复现你的情况的。

**Comment by seinteller** [comment]
你好, 我想安裝上出了問題, 所以才下載不了。現在可以,下載到了, 謝謝。
但又一個新的問題, 
在cmd cd到安裝的文件夾內輸入.\.venv\Scripts\activate
然後打開 .py 檔, 運作正常

但如果是直接用windows中的Python打開就會顯示
"ModuleNotFoundError: No module named 'linovelib2epub'"
但我在pip list 是可以見到linovelib2epub...

.venv 是必須每次手動打開?
Python 新手, 問題很多, 麻煩你了。

**Comment by wdpm** [comment]
@seinteller 

venv是 python 3.5+ 创建虚拟环境的模块。在 windows系统下，
- `.\.venv\Scripts\activate`表示激活虚拟环境，
- 然后 `py -m pip install -r requirements.txt`是表示在这个虚拟环境中安装项目依赖，
- 最后 `python -m pip install -e .`表示将这个linovelib2epub模块以编辑模式（-e）安装到这个虚拟环境中。

因此，这一切都是为了将项目依赖和本项目安装到一个特定的虚拟环境中。这么做的原因是为了隔离python项目的运行环境，因为python全局依赖只能有一个软件版本，而本地电脑往往有多个python项目。这是基于python项目开发的最佳实践而采用的隔离做法。

## 问题答疑

> 但如果是直接用windows中的Python打開就會顯示
"ModuleNotFoundError: No module named 'linovelib2epub'"
但我在pip list 是可以見到linovelib2epub...

你在这里见到的 linovelib2epub 可能是你以前从pypi下载的linovelib2epub，那是很旧的代码了，已经不可用了。

例如：
```bash
> pip list
linovelib2epub                 0.1.2
```
如果你在全局python环境下运行demo.py，就会发现内容是None的情况。

目前你没法在全局方式简便地运行该项目，因为我很久都没有发布 pypi 的最新包了，爬虫变化太快，后续我不打算发布pypi 包，请经常update源码，以源码模式安装。

---

> .venv 是必須每次手動打開?

对的，必须打开。示意图：
```bash
(venv) wdpm  linovelib2epub  ➜ (main)  ♥ 12:02  pip list
Package              Version     Editable project location
-------------------- ----------- ----------------------------------------
aiofiles             23.1.0
aiohttp              3.8.4
aiologger            0.7.0
aiosignal            1.3.1
ansicon              1.89.0
......
linovelib2epub       0.1.3       D:\Code\lightnovel-center\linovelib2epub
```
 `D:\Code\lightnovel-center\linovelib2epub`表示的是一个本地路径，也就是源码模式的安装。
---

参阅：
- [venv](https://docs.python.org/zh-cn/3/library/venv.html#module-venv) --- 创建虚拟环境

**Comment by seinteller** [comment]
謝謝你的詳盡分享! ^^

**Comment by wdpm** [comment]
> 謝謝你的詳盡分享! ^^

不客气，如果有其他疑问，也可以大胆继续提问。如果该issue已被解决的话，请你自行关闭issue。
