### ISSUE TITLE
WENKU8 問題

### ISSUE THREAD

**Issue by seinteller** [lightnovel-center/linovelib2epub#23]
做了一個.py 執行以下碼, 直接閃退, LOG 也沒有留下... 
求協助, 謝謝
from linovelib2epub import Linovelib2Epub, TargetSite

if __name__ == '__main__':
    linovelib_epub = Linovelib2Epub(book_id=2961, target_site=TargetSite.WENKU8)
    linovelib_epub.run()

**Comment by wdpm** [comment]
> 做了一個.py 執行以下碼, 直接閃退, LOG 也沒有留下... 求協助, 謝謝 from linovelib2epub import Linovelib2Epub, TargetSite
> 
> if **name** == '**main**': linovelib_epub = Linovelib2Epub(book_id=2961, target_site=TargetSite.WENKU8) linovelib_epub.run()

我现在本地的wenku8也是拿不到结果的，我需要排查是不是也需要登录验证了。游客方式是存在被拒绝访问的情况的，防护墙越来越高了。

**Comment by wdpm** [comment]
@seinteller 

```python
from linovelib2epub import Linovelib2Epub, TargetSite

if __name__ == '__main__':
    linovelib_epub = Linovelib2Epub(book_id=2961, target_site=TargetSite.WENKU8, disable_proxy=False)
    linovelib_epub.run()
```
1. 更新仓库代码
2. 按照上面的py文件来执行一次，观察是否正常运行。上面 disable_proxy=False 的作用是启用本地代理环境。我在本地测试发现是可行的，但是爬虫速度很慢。

**Comment by wdpm** [comment]
fixed by [#c3eb6e54](https://github.com/lightnovel-center/linovelib2epub/commit/c3eb6e54c8ae5651efd89cfbec82470e1e0f87f2)

**Comment by Kuan-Lun** [comment]
> 游客方式是存在被拒绝访问的情况的，防护墙越来越高了。

經測試，遊客方式仍然可以正常訪問；遊客不能進主頁，但若有小說網址還是可以進入；如[範例](https://www.wenku8.net/novel/3/3138/index.htm)。

**Comment by wdpm** [comment]
> > 游客方式是存在被拒绝访问的情况的，防护墙越来越高了。
> 
> 經測試，遊客方式仍然可以正常訪問；遊客不能進主頁，但若有小說網址還是可以進入；如[範例](https://www.wenku8.net/novel/3/3138/index.htm)。
> 

这个issue的时间有点久远了。已经不能反映当时的情况了。其实可以关闭，后续我清理issue时我就会关闭它。
