### ISSUE TITLE
content_id can't be empty string

### ISSUE THREAD

**Issue by fmd12345** [lightnovel-center/linovelib2epub#24]
从git clone下载安装的最新版本
使用默认源，bookid=75时，运行报错
AssertionError: content_id can't be empty string, please submit this bug to github issue.

**Comment by wdpm** [comment]
感谢反馈。这个问题的原因在于哔哩轻小说又又又修改js加密规则了😶。
需要一定时间来进行js反编译，请留意后续进展。@fmd12345

**Comment by wdpm** [comment]
已经回滚js反编译的逻辑。你可以再次确认。@fmd12345

**Comment by fmd12345** [comment]
> 已经回滚js反编译的逻辑。你可以再次确认。@fmd12345

测试可以了，感谢
