### ISSUE TITLE
抱歉，章节内容不支持该浏览器显示～ (linovelib ID 3721)

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#38]
ID 3721

下載的 EPub 中，每一個章節都內文顯示如下
```
(ò﹏ò)
抱歉，章节内容不支持该浏览器显示～
【为了使用完整的阅读功能】
请考虑使用〔Chrome 谷歌浏览器〕、〔Safari 苹果浏览器〕或者
〔Edge 微软浏览器〕等原生浏览器阅读！
谢谢!!!
```

我使用瀏覽器是能正常訪問文章內容。

**Comment by wdpm** [comment]
该问题已被确认。原因是bilinovel又修改反爬虫策略了。解决方案还需要进一步探索。

**Comment by wdpm** [comment]
已修复。更新代码，更新依赖，以验证是否修复。

**Comment by Kuan-Lun** [comment]
一是 ID 3721，仍有問題。

'''
2024-03-15,15:35:35 INFO     LinovelibMobileSpider Succeed to get the novel of book_id: 3721                                                                                                                                            linovelib_mobile_spider.py:84
                    INFO     LinovelibMobileSpider book name:《乱世千金倪亚・利斯顿》                                                                                                                                                   linovelib_mobile_spider.py:94
                    INFO     LinovelibMobileSpider Succeed to get the catalog of book_id: 3721                                                                                                                                         linovelib_mobile_spider.py:144
                    INFO     LinovelibMobileSpider volume: 第一卷                                                                                                                                                                      linovelib_mobile_spider.py:160
                    INFO     LinovelibMobileSpider chapter : 插图                                                                                                                                                                      linovelib_mobile_spider.py:175

DevTools listening on ws://127.0.0.1:62433/devtools/browser/f6f82007-4288-47c4-854a-33efab67be19
2024-03-15,15:35:46 INFO     LinovelibMobileSpider  初始化 Driver 完毕...    
Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 30, in <module>
    linovelib_epub.run()
  File "[path]\linovelib2epub-main\src\linovelib2epub\linovel.py", line 412, in run
    novel = self._spider.fetch()
            ^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 53, in fetch
    novel_whole = self._fetch()
                  ^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 474, in _fetch
    new_novel_with_content = self._crawl_book_content(book_catalog_url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 193, in _crawl_book_content
    if not new_title.text.startswith(light_novel_chapter.title):
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
'''

**Comment by wdpm** [comment]
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/55013210-47fa-4c70-8758-b4c561baff8a)

提供一下你爬虫时类似这个的截图。

AttributeError: 'NoneType' object has no attribute 'text' 这个错误指的是找不到文章标题。

但是我这边是没法复现的，我暂时不清楚是为何会出现这个问题。

**Comment by Kuan-Lun** [comment]
![VOacd4A](https://github.com/lightnovel-center/linovelib2epub/assets/33048725/06935aaf-0a00-465b-8d64-ab3d2c6ba053)

```
2024-03-15,21:19:52 INFO     LinovelibMobileSpider Succeed to get the novel of book_id: 3721                                                                                                                                            linovelib_mobile_spider.py:84
                    INFO     LinovelibMobileSpider book name:《乱世千金倪亚・利斯顿》                                                                                                                                                   linovelib_mobile_spider.py:94
                    INFO     LinovelibMobileSpider Succeed to get the catalog of book_id: 3721                                                                                                                                         linovelib_mobile_spider.py:144
                    INFO     LinovelibMobileSpider volume: 第一卷                                                                                                                                                                      linovelib_mobile_spider.py:160
                    INFO     LinovelibMobileSpider chapter : 插图                                                                                                                                                                      linovelib_mobile_spider.py:175

DevTools listening on ws://127.0.0.1:62529/devtools/browser/feb744e3-d24e-4e5d-b57d-f97a1233dc25
2024-03-15,21:19:57 INFO     LinovelibMobileSpider  初始化 Driver 完毕...                                                                                                                                                              linovelib_mobile_spider.py:297
Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 30, in <module>
    linovelib_epub.run()
  File "[path]\linovelib2epub-main\src\linovelib2epub\linovel.py", line 412, in run
    novel = self._spider.fetch()
            ^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 53, in fetch
    novel_whole = self._fetch()
                  ^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 474, in _fetch
    new_novel_with_content = self._crawl_book_content(book_catalog_url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 193, in _crawl_book_content
    if not new_title.text.startswith(light_novel_chapter.title):
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by wdpm** [comment]
将你上面这个 https://tw.linovelib.com/novel/3721/190988.html 这个网页源文件下载后，发送到这个issue下面。

**Comment by Kuan-Lun** [comment]
我使用 Chrome 瀏覽器開啟後進行儲存，參見[檔案](https://gofile.io/d/DQfnvN)。

**Comment by wdpm** [comment]
> 我使用 Chrome 瀏覽器開啟後進行儲存，參見[檔案](https://gofile.io/d/DQfnvN)。

我看了，格式没问题。估计是其他原因。

**Comment by wdpm** [comment]
我在代码中添加了debug代码。你更新后尝试下面的代码，将前面一部分log发上来看看。

```python
from linovelib2epub import Linovelib2Epub

if __name__ == '__main__':
    linovelib_epub = Linovelib2Epub(book_id=3721, clean_artifacts=False,log_level='DEBUG')
    linovelib_epub.run()
````

**Comment by wdpm** [comment]
> 我看了一下日志，问题的原因是触发了之前说的访问频率限制 https://github.com/lightnovel-center/linovelib2epub/issues/36 ，但是程序没有重试，导致爬到的是空内容。
你和上面的 @Kuan-Lun 遇到的情况不一样，@Kuan-Lun是直接抛异常，连正常页面内容都拿不到。你是后续请求触发风控限制，导致无法访问。

**Comment by wdpm** [comment]
try to fix by https://github.com/lightnovel-center/linovelib2epub/commit/b50353792a45e15b0fd1af2a6101dcf90013a752

**Comment by Kuan-Lun** [comment]
> 我在代码中添加了debug代码。你更新后尝试下面的代码，将前面一部分log发上来看看。 PS: 日志会很长，你只需要提供前面一部分即可。
> 
> ```python
> from linovelib2epub import Linovelib2Epub
> 
> if __name__ == '__main__':
>     linovelib_epub = Linovelib2Epub(book_id=3721, clean_artifacts=False,log_level='DEBUG')
>     linovelib_epub.run()
> ```

詳細請參見[檔案](https://gofile.io/d/KqInaY)，以下為前 20 行。

```
(.venv) PS [path]\linovelib2epub-main> python .\main.py
2024-03-18,16:56:59 INFO     LinovelibMobileSpider Succeed to get the novel of book_id: 3721                                                                                                          linovelib_mobile_spider.py:85
                    INFO     LinovelibMobileSpider book name:《乱世千金倪亚・利斯顿》                                                                                                                 linovelib_mobile_spider.py:95
                    INFO     LinovelibMobileSpider Succeed to get the catalog of book_id: 3721                                                                                                       linovelib_mobile_spider.py:145
                    INFO     LinovelibMobileSpider volume: 第一卷                                                                                                                                    linovelib_mobile_spider.py:161
                    INFO     LinovelibMobileSpider chapter : 插图                                                                                                                                    linovelib_mobile_spider.py:176

DevTools listening on ws://127.0.0.1:49158/devtools/browser/213e932b-ce10-4e1b-9938-4b70540147c7
2024-03-18,16:57:05 INFO     LinovelibMobileSpider  初始化 Driver 完毕...                                                                                                                            linovelib_mobile_spider.py:334
2024-03-18,16:57:08 DEBUG    LinovelibMobileSpider page_resp='<html lang="zh-Hant"><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>亂世千金倪亞・利斯頓 第一卷   linovelib_mobile_spider.py:186
                             插圖_嗶哩輕小說</title>\n<meta name="keywords" content="亂世千金倪亞・利斯頓,插圖,嗶哩輕小說">\n<meta name="description"
                             content="拥有最强前世的转生千金，第二人生也要大闹天下！！\n「既然人难免一死，我宁可死在战斗中。」\n过去曾有..">\n<meta name="viewport"
                             content="initial-scale=1.0,minimum-scale=1.0,user-scalable=yes,width=device-width">\n<meta name="theme-color" content="#232323" media="(prefers-color-scheme:
                             dark)">\n<meta name="applicable-device" content="mobile">\n<link rel="stylesheet" href="https://tw.linovelib.com/themes/zhmb/css/read.css?v0409a1">\n<link
                             rel="stylesheet" href="https://tw.linovelib.com/themes/zhmb/css/chapter.css?v1126a2">\n<link rel="dns-preconnect" href="https://tw.linovelib.com">\n<link
                             rel="prerender" href="https://tw.linovelib.com/novel/3721/190989.html">\n<link rel="alternate" hreflang="zh-Hans"
                             href="https://www.bilinovel.com/novel/3721/190988.html">\n<script
                             src="https://pagead2.googlesyndication.com/pagead/managed/js/adsense/m202403130201/slotcar_library_fy2021.js"></script><script
                             src="https://pagead2.googlesyndication.com/pagead/managed/js/adsense/m202403130201/reactive_library_fy2021.js"></script><script
                             src="https://pagead2.googlesyndication.com/pagead/managed/js/adsense/m202403130201/show_ads_impl_fy2021.js"></script><script
```

**Comment by GOKORURI007** [comment]
> 这个每页爬取延迟或者也可以提取为一个用户可以指定的API参数，将更大的控制权交给用户。
例如，新增一个page_crawl_delay参数，可以设置为 指数退避标记，或者固定时间例如3s。

@wdpm 这个想法不错，如果只能默认使用指数退避方法的话，前几次重试间隔过低可能导致多次触发访问限制，尽量少的触发风控限制对网站管理员和用户都是有利的。因此，至少对于linovellib这个网站来说，提供一个固定时间的选项能够更好的规避服务器访问频率限制。

另外，我个人认为与其为重试间隔添加一个固定延迟，不如像chapter_crawl_delay这样，不管是否触发风控都为fetch_page添加一个固定延迟。
实际测试中，我用类似chapter_crawl_delay的方式添加了一个page_crawl_delay，在chapter_crawl_delay=5，page_crawl_delay=3的情况下成功爬取了linovellib上的整本小说且没有触发风控限制，因此可以考虑为fetch_page添加一个固定延迟API参数，重试延迟直接采用指数退避方式即可。
```python
for page_link in catalog_chapter.chapter_urls:
        # use selenium instead of direct requests
        # 此处添加page_crawl_delay()
        time.sleep(3)     # 测试时我直接在这里添加了time.sleep()
        # self._fetch_page方法内部的重试延迟沿用指数退避方法
        page_resp = self._fetch_page(page_link, max_retries=self.spider_settings['http_retries'])
        self.logger.debug(f'{page_resp=}')
```

**Comment by wdpm** [comment]
update by https://github.com/lightnovel-center/linovelib2epub/commit/3ec5c9502d7c775a7db91834bbfd09e7263b2866
@GOKORURI007
