### ISSUE TITLE
epub格式相关

### ISSUE THREAD

**Issue by xxxfhy** [lightnovel-center/linovelib2epub#4]
- 使用这个库的过程中发现需要先安装pillow库，同时需要降级setuptools版本到57.5.0避免use_2to3 is invalid错误
- 文件在starrea，EPubBuilder上无法打开

-附测试文件
[没有明天的我们，在昨天相恋.zip](https://github.com/lightnovel-center/linovelib2epub/files/10488068/default.zip)

**Comment by wdpm** [comment]
@xxxfhy 我更新了有关在本地使用该库的[说明](https://github.com/lightnovel-center/linovelib2epub#install-from-source)

**Comment by wdpm** [comment]
0.0.10 版本已经发布，你可以再次测试。先溜了。

**Comment by wdpm** [comment]
那其实你的问题在我看来不是问题，你的问题是特定epub阅读器不能阅读的问题。我又不用你给出的epub软件，而且**不可能是epub文件去适配epub阅读软件**。
epub规范是一种标准，**任何下游的epub阅读软件都应该去遵循epub2&3标准，按照标准方式去解析渲染**。市面上其实很多epub阅读软件的兼容性都很一般，包括我上面列出的那些。基本都有渲染错误的情况出现。

如果这个问题没啥事了，那就关闭这个issue吧。如果有其他问题，可以另起issue来提问。

**Comment by zhuxinghan** [comment]
Starrea 已修复不能打开这本书的问题
