### ISSUE TITLE
建议实现rate limit功能

### ISSUE THREAD

**Issue by haruki-nikaidou** [lightnovel-center/linovelib2epub#41]
不加rate limit容易把网站爬挂掉，一直报错502.

建议的实现：允许通过参数设置基础延迟，sleep之后再请求下一页

**Comment by wdpm** [comment]
- 第一个需要细化的细节：这个基础延迟指的是chapter_crawl_delay还是page_crawl_delay？
- 第二个细节：你指的是哪一个target site？印象中linovelib已经有上面的延迟机制了。

**Comment by wdpm** [comment]
- 第一个需要细化的细节：这个基础延迟指的是chapter_crawl_delay还是page_crawl_delay？
- 第二个细节：你指的是哪一个target site？印象中linovelib已经有上面的延迟机制了。
