### ISSUE TITLE
[BUG] requirements.txt 需更新或添加限定 Python 版本等資訊

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#44]
**Describe the bug（描述这个BUG）**
如目前要求使用的 pillow 版本 9.2.0 並不運作於 Python 3.12，需要使用 10 以上版本。
(還有 lxml 等套件也有同樣的問題)

**Expected behavior（期望的行为）**

於說明文件添加 Python 版本的限制，或將 requirements.txt 內的 == 改為 >=。

個人是建議使用 setuptools 的 step.py 撰寫相依套件，這可以做比較細節的環境處理。

**Comment by wdpm** [comment]
感谢你留意到这个关于python版本兼容性的问题。
pillow版本 [官方文档](https://pillow.readthedocs.io/en/stable/installation/python-support.html) 中对此进行了详细的说明：
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/63510715-8598-402b-af13-64a2b1a3d82c)

而 [python status](https://devguide.python.org/versions/#status-of-python-versions) 为：
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/da5fcef6-36b0-484b-a40c-c7766f5a585b)

目前版本python 3.10+ pillow 9.2.0这个组合的确过于局限了。

我认为应该扩大兼容范围，提升pillow版本到 >=10.1 来兼容 python 3.10-3.13

**Comment by wdpm** [comment]
> 個人是建議使用 setuptools 的 step.py 撰寫相依套件，這可以做比較細節的環境處理。

setup.py只是一种传统的使用python代码来定义python项目依赖构建的方式，和目前这个项目在用的 *.toml配置并没有太本质的区别。

**Comment by wdpm** [comment]
暂时不会花太多精力来处理这个依赖更新的问题。目前仅更新pillow到 >=10.1
```
bs4==0.0.1
demjson3==3.0.5
EbookLib==0.17.1
fake-useragent==1.1.1
requests==2.28.1
rich==12.5.1
uuid==1.30
pillow==10.1.0           <---------------
inquirer==3.1.2
aiofiles==23.1.0
aiohttp==3.8.4
dynaconf==3.2.3
brotli==1.1.0
lxml==4.9.2
tabulate==0.9.0
DrissionPage==4.0.4.5
selenium==4.17.2
esprima==4.0.1
```
