### ISSUE TITLE
[BUG] 疯狂刷新触发风控导致无法正常进行下载

### ISSUE THREAD

**Issue by sweetnotice** [lightnovel-center/linovelib2epub#46]
**Describe the bug（描述这个BUG）**
选择章节进行下载后，浏览器会疯狂刷新，然后触发风控。浏览器以及驱动已确定为最新版 `124.0.6367.91`

**To Reproduce（复现步骤）**
```python
from linovelib2epub import Linovelib2Epub

if __name__ == '__main__':
    # /path/to/chromedriver
    browser_driver_path = r'C:\Users\Administrator\Desktop\chromedriver-win64\chromedriver.exe'
    linovelib_epub = Linovelib2Epub(book_id=8, chapter_crawl_delay=3, page_crawl_delay=2, select_volume_mode=True,
                                    browser_driver_path=browser_driver_path,
                                    log_level='DEBUG')
    linovelib_epub.run()

```

**Screenshots or Video（截图或者视频录制）**
![image](https://github.com/lightnovel-center/linovelib2epub/assets/106159757/52f6d4f7-5cdc-40fd-979c-fcab292a95f3)

**Environment（软件环境）**
 - OS Verison:  例如：Windows 10 专业版22h2
 - Python Version: `Python 3.10.9`
 - Pip Version: `pip --version`

**Additional context（补充信息[可选]）**
[www.bilinovel.com_8.log](https://github.com/lightnovel-center/linovelib2epub/files/15137478/www.bilinovel.com_8.log)

**Comment by wdpm** [comment]
文档中已经对此进行了说明，这是一个已知的缺陷。
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/57a49739-a774-48ad-9646-ef780325df27)
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/d66fd99e-ed60-46f7-a448-b3ad0ec467d4)

由于 selenium 的浏览器特征指纹太老，在2024年来看，已经是强弩之末了。
后续我可能会将其改为目前较为隐蔽的 DrissionPage 库。

**Comment by sweetnotice** [comment]
感谢回答。请问您有什么好办法可以还原每话最后的那一段js后加载的字库混淆文字吗。js混淆强度好高，让我这个不怎么了解js的小白望而却步了

**Comment by wdpm** [comment]
> 感谢回答。请问您有什么好办法可以还原每话最后的那一段js后加载的字库混淆文字吗。js混淆强度好高，让我这个不怎么了解js的小白望而却步了

具体描述下你的疑问，你这样问我不清楚你的疑惑点。

**Comment by sweetnotice** [comment]
额，不是关于软件的问题，而是网站逆向方面的一些问题，现在哔哩轻小说又更新加密了。每话最后的一段文本不使用以前的js 正则替换 而改为使用字库进行替换，我也做过尝试，但还是解决不了，所以请教大佬给点思路
![image](https://github.com/lightnovel-center/linovelib2epub/assets/106159757/da33a3f5-3ae1-4159-926c-1b970da02df8)

**Comment by wdpm** [comment]
给你上面这个截图的文章页链接地址给我，我去看下。

**Comment by sweetnotice** [comment]
> 给你上面这个截图的文章页链接地址给我，我去看下。

[pc端](https://www.linovelib.com/novel/2600/141708_2.html)
[移动端](https://www.bilinovel.com/novel/2600/141708_2.html)
据我所知这个加密已经上线有一段时间了，pc端一个礼拜左右，移动端是最近上线的。
能很明显的看到最后一段话字体与别的文字不一样

**Comment by wdpm** [comment]
寄，目前 linovelib 应该设置了IP黑名单机制了。我在本地也没法测试我的解决方案。

**Comment by sweetnotice** [comment]
> 寄，目前 linovelib 应该设置了IP黑名单机制了。我在本地也没法测试我的解决方案。 估计要尽快将selenium切换到 DrissionPage，~快进到自研爬虫浏览器指纹。(bushi)~

祝大佬武运昌盛。另外我觉得可以不依赖浏览器的，可以纯get请求再加js逆向，这样运行可以更稳。佬可以看看我的仓库。
[Bilinoval_DL](https://github.com/sweetnotice/Bilinoval_DL)之前都是可以稳定运行的，就是因为最近加了个这个东西，我只会简单的js逆向，没学过js。。。

**Comment by wdpm** [comment]
@sweetnotice 这个项目以前就是使用 requests这种的，后来被迫改为无头浏览器。
因为拦截点太多了，例如：
- cloudflare 过风控检测
- CSS渲染，或者补JS环境来复原混淆
- 可能以后还会出现各种奇奇怪怪的验证码
- ...

纯API请求我认为是一条绝路，因为linovelib这类网站只会更加严控爬虫。
我暂时没时间来探索其他的仓库，这个项目的维护其实也不是很活跃。

**Comment by sweetnotice** [comment]
确实。DrissionPage其实也挺完美的
- 能过cloudflare
- 能抓包
- 所见即所得
- 以前麻烦的点是得自己装Chromedriver，现在也解决了
- 最重要的是比逆向那些恶心的js例如瑞数花的时间成本低

除了在内存低的机器上不太好运行，不方便调试外没有缺点了。
哔哩轻小说什么时候才能开放注册啊，等了快半年了，实在没办法才做的爬虫，它有功夫做反爬不如给他那个注册开开。哎

**Comment by wdpm** [comment]
@sweetnotice 这个问题已被间接修复。
目前 mobile 版本即手机版本的linovelib，我也没法突破cloudflare。因此我改为爬取它的PC版本即电脑版本。
关于字体混淆的研究与解决方案，我记录在了这个md文件中，如果你感兴趣，可以查看 [linovelib-pc-font-obfuscation](https://github.com/lightnovel-center/linovelib2epub/blob/main/docs-internal/linovelib-pc-font-obfuscation.md)。

关于最新版本代码，请更新项目源码并仔细阅读README文档来运行。

**Comment by sweetnotice** [comment]
牛啊老哥.
使用ocr的方式确实是修上了,它那个字库字太多了,用ocr做字体映射也麻烦.直接ocr网页确实是一个聪明的想法
也许可以让用户自行选择设置ocr接口 例如 '百度ocr' 什么的,获得更精确的识别体验

**Comment by wdpm** [comment]
> 也许可以让用户自行选择设置ocr接口 例如 '百度ocr' 什么的,获得更精确的识别体验

目前只有少部分章节的某些页面的最后一个段落p存在CSS 字体混淆，我认为混淆面积比例不大，而且pytesseract的识别率对于简体/繁体/english的识别准确率并不低。因此在目前阶段我不会考虑增强OCR。

> 可以将 DrissionPage 的page设置为 eager模式 参考官网文档 [DrissionPage 加载模式](https://drissionpage.cn/ChromiumPage/visit) 用来只加载页面文字以减轻网络负担,加快请求速度

你的想法是很好的，可是事实上却不能这样做。因为仅加载页面文字是不足够的，必须完全加载整个页面，同时必须渲染CSS样式，以及执行关于JS恢复混淆的相关逻辑。
- 渲染CSS样式：程序中需要获取相关活跃的CSS样式表，来判断当前页面是否存在字体混淆。
- JS恢复混淆：这是pctheme.js中的一个逻辑，网页源码是根据混淆表（一个dict）混淆后的，JS会把他们复原。
因此，CSS样式渲染和JS执行缺一不可，所以eager模式不适用。
@sweetnotice

**Comment by sweetnotice** [comment]
经过我本地测试,eager模式是可以正常工作的,可以正常显示需要用js复原的字体,这是我简化后不完全代码
```
# 这是您给出的js代码
js_check = """
const last_p = document.querySelector('#TextContent p:last-of-type')
const p_style = window.getComputedStyle(last_p)
const p_font_style = p_style.getPropertyValue('font-family')
if (p_font_style && p_font_style.includes('read')) {
    return true;
}
return false;
"""

def dp_get_chapter_text(chapter_url):
    page = ChromiumPage()
    page.set.load_mode.eager()  # 设置为eager模式 加载完 DOM 或超时即停止加载，不加载页面资源
    page.get(chapter_url, timeout=5, retry=2)

    texts = ''
    text = page.ele('x://*[@id="TextContent"]').html  # 获取章节文本
    text = re.sub('<div class="google-auto-placed.*?</ins></div>', '', text)  # 去除谷歌广告
    text = re.sub('<ins class="adsbygoogle".*?</ins>', '', text)
    texts += text
    if page.run_js(js_check):
        last_p = page.ele('css:#TextContent p:last-of-type')
        base64_pic = last_p.get_screenshot(as_base64='png')  # 返回截图二进制文本
        ocr_word = ocr_api.high_precision_ocr(base64_pic) # 使用百度ocr识别
        texts = texts.replace(last_p.text, ocr_word)
```

**Comment by wdpm** [comment]
经过简单的本地测试，eager 模式的确可行，性能提升为一个页面从平均1s到0.3s，提升幅度为 0.7s/1.0s *100=70%。
@all-contributors add @sweetnotice as a contributor for bug.
