### ISSUE TITLE
[不是BUG] 一直在重复获取图片

### ISSUE THREAD

**Issue by 2655196510** [lightnovel-center/linovelib2epub#51]
**Describe the bug（描述这个BUG）**
一直在重复获取插图

**To Reproduce（复现步骤）**
```
from linovelib2epub import Linovelib2Epub, TargetSite

if __name__ == "__main__":
    linovelib_epub = Linovelib2Epub(book_id=2407, target_site=TargetSite.LINOVELIB_PC,
                                    chapter_crawl_delay=5, page_crawl_delay=3,
                                    select_volume_mode=True,
                                    disable_proxy=False,
                                    log_level="DEBUG",
                                    )

    linovelib_epub.run()
```

**日志**
[www.linovelib.com_2407.log](https://github.com/user-attachments/files/17269411/www.linovelib.com_2407.log)

**Screenshots or Video（截图或者视频录制）**
截图
![2](https://github.com/user-attachments/assets/b4a3a241-8c35-47f8-a6f0-43fe71128a29)
视频

https://github.com/user-attachments/assets/b896f043-1351-48e9-9782-203090959891

**Environment（软件环境）**
 - OS Verison:  例如：Windows 10 专业版1903（18362.175）
 - Python Version: ` 3.10.11`
 - Pip Version: `pip 23.2.1`

Additional context（补充信息[可选]）
里面的插图链接在浏览器是可以打开的
![捕获](https://github.com/user-attachments/assets/ce789d9c-6823-44ac-8117-06776cc9cb00)

**Comment by wdpm** [comment]
## 分析
@2655196510 先说结论。从开发者角度来看，这个不是BUG，而是因为目标服务器（指Linovelib）或者你所在的网络环境导致请求插图失败了。

我尝试在本地复现你这个问题，结果是请求图片重试的逻辑是正常的。

图片下载重试的部分关键日志如下：
![image](https://github.com/user-attachments/assets/02714442-2235-4adb-bec5-1a3b7677d495)
![image](https://github.com/user-attachments/assets/9dc540ac-5d27-4f5b-9019-583123107b0e)

- ServerTimeoutError 指的是Linovelib服务器超时。
- TimeoutError 指的是你PC和Linovelib之间网络往返发生超时。

## 解决方案
我认为程序逻辑是正常的，你可以换个时间段来重试，或者更换你的本地网络VPN环境（如果有的话）。

**Comment by 2655196510** [comment]
换了几个机场好像还是不行
![捕获](https://github.com/user-attachments/assets/b0ebc1d8-1a45-42d3-97a8-5e3a409d52e4)
还有其他解决方法吗？

**Comment by wdpm** [comment]
> 换了几个机场好像还是不行
> ![捕获](https://github.com/user-attachments/assets/b0ebc1d8-1a45-42d3-97a8-5e3a409d52e4)
> 还有其他解决方法吗？

disable_proxy=True 试试。这个是禁用代理。

**Comment by 2655196510** [comment]
禁用之后
![捕获](https://github.com/user-attachments/assets/a764b9e4-d56f-4722-aeeb-c6b6eb1457ce)

**Comment by 2655196510** [comment]
禁用代理，关闭clash是这样
![1](https://github.com/user-attachments/assets/66118ad4-a1ac-4bb2-979c-6f0e629e39ac)
禁用代理，启用clash是这样
![2](https://github.com/user-attachments/assets/0481e2a0-666c-4771-a522-2e27a09c6560)

**Comment by 2655196510** [comment]
第二种情况的后续又变成循环超时了
![3](https://github.com/user-attachments/assets/ca7a9598-3f4d-4d84-810b-8eea8fbd26c9)

**Comment by wdpm** [comment]
len of image list 为何你的截图中是1。这数据不对劲。

**Comment by 2655196510** [comment]
啥

**Comment by wdpm** [comment]
> len of image list 为何你的截图中是1。这数据不对劲。已经很晚了。下次有空再远程帮你看下吧。

**Comment by 2655196510** [comment]
麻烦了，嘿嘿

**Comment by 2655196510** [comment]
学校还有台笔记本，明天我回学校再看看

**Comment by wdpm** [comment]
> 学校还有台笔记本，明天我回学校再看看

后续这个问题如果在你那边还是没解决的话，留个联系方式，例如QQ或者discord之类，再商量找个空闲时间看下。
