### ISSUE TITLE
命名问题

### ISSUE THREAD

**Issue by xxxfhy** [lightnovel-center/linovelib2epub#7]
[转生王女和天才千金的魔法革命【Web版】](https://www.linovelib.com/novel/3573/catalog)有两个相同的章节名，会导致分卷下载时上一章被吞

**Comment by wdpm** [comment]
![Snipaste_2023-02-01_11-15-07](https://user-images.githubusercontent.com/14016242/215936531-041e4a03-b9b9-4760-b31c-3f8a4a629d76.png)

这个？

我知道了。目前代码没有考虑到volume name重复的问题，而是直接使用这个volume name作为dict的key。因此会出现key覆盖的问题。等下一次修复吧，目前我在重写这个项目，可能需要点时间。

**Comment by wdpm** [comment]
https://pypi.org/project/linovelib2epub/0.0.12/

@xxxfhy 用这个版本试试。重构代码太多，可能会引入其他问题。
