### ISSUE TITLE
.txt下載

### ISSUE THREAD

**Issue by watercup0926** [lightnovel-center/linovelib2epub#9]
可以讓她下載.txt嗎，或著分捲下載?

**Comment by wdpm** [comment]
- 分卷输出：这个功能已经有了，使用文档中的 divide_volume=True 选项就是启用分卷输出的模式。
- 分卷下载：我猜测你想说的是选择卷的模式，也已经有了，select_volume_mode=True 就是启用选择卷。例如，对于一本书，可以挑选第1卷、第6卷进行下载，并分卷输出为独立的epub。选择卷模式，会在command line提示卷列表，按需选择即可。

TXT下载功能，这个功能暂时没有。主要是我个人一直认为没有必要，因为已经有网站提供了很完整的无门槛的txt下载功能。
你可以暂时使用 https://www.wenku8.net/ （它其实没有关闭网站的，可以注册登陆）来进行下载TXT。

例如：https://www.wenku8.net/modules/article/packshow.php?id=2290&type=txt 这个形式的链接。可以分卷下载。


如果你有其他疑问，可以继续提出。
